sudo: false

language: node_js

node_js:
  - "8"

branches:
  only:
    - master

notifications:
  email:
    on_failure: change
    on_success: change
  slack:
    rooms:
      - celebro:wrLBg1mqY4MuL3yHX4itbAbA#react-cms

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  # TODO: Use npm again functions runtime is updated to a node verion with lock files
  - yarn install

script:
  - npm run lint
  # - npm run test
  - npm run release

after_success:
  - npm run deploy

addons:
  code_climate:
    repo_token: 671eb6f25585825b98eeac395c3d1ddea379f38402c00ac61d77afdbe0ebb926
